-- MySQL -- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 17:46:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Incidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Incidente` (
  `idTipo_Incidente` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idTipo_Incidente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tecnicos` (
  `idTecnicos` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Apellido` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  `Edad` INT NOT NULL,
  `Turno` VARCHAR(45) NOT NULL,
  `Disponibilidad` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idTecnicos`),
  UNIQUE INDEX `Nombre_Apellido_UNIQUE` (`Nombre_Apellido` ASC) VISIBLE,
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operador` (
  `idOperador` INT NOT NULL,
  `Nombre_Apellido` VARCHAR(45) NOT NULL,
  `Turno` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  `CUIT` INT NOT NULL,
  PRIMARY KEY (`idOperador`),
  UNIQUE INDEX `Nombre_Apellido_UNIQUE` (`Nombre_Apellido` ASC) VISIBLE,
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  UNIQUE INDEX `CUIT_UNIQUE` (`CUIT` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Incidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Incidente` (
  `idIncidente` INT NOT NULL,
  `FechaInicial` DATE NOT NULL,
  `FechaFinal` DATE NOT NULL,
  `Descripcion` LONGTEXT NOT NULL,
  `Estado` TINYINT NOT NULL DEFAULT 0,
  `Tipo_Incidente_idTipo_Incidente` INT NOT NULL,
  `Tecnicos_idTecnicos` INT NOT NULL,
  `Operador_idOperador` INT NOT NULL,
  PRIMARY KEY (`idIncidente`, `Tipo_Incidente_idTipo_Incidente`),
  INDEX `fk_Incidente_Tipo_Incidente1_idx` (`Tipo_Incidente_idTipo_Incidente` ASC) VISIBLE,
  INDEX `fk_Incidente_Tecnicos1_idx` (`Tecnicos_idTecnicos` ASC) VISIBLE,
  INDEX `fk_Incidente_Operador1_idx` (`Operador_idOperador` ASC) VISIBLE,
  CONSTRAINT `fk_Incidente_Tipo_Incidente1`
    FOREIGN KEY (`Tipo_Incidente_idTipo_Incidente`)
    REFERENCES `mydb`.`Tipo_Incidente` (`idTipo_Incidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidente_Tecnicos1`
    FOREIGN KEY (`Tecnicos_idTecnicos`)
    REFERENCES `mydb`.`Tecnicos` (`idTecnicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidente_Operador1`
    FOREIGN KEY (`Operador_idOperador`)
    REFERENCES `mydb`.`Operador` (`idOperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tec_Especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tec_Especialidades` (
  `idTec_Especialidades` INT NOT NULL AUTO_INCREMENT,
  `Tipo/Nombre` VARCHAR(60) NOT NULL,
  `Tipo_Incidente_idTipo_Incidente` INT NOT NULL,
  PRIMARY KEY (`idTec_Especialidades`, `Tipo_Incidente_idTipo_Incidente`),
  UNIQUE INDEX `Tipo/Nombre_UNIQUE` (`Tipo/Nombre` ASC) VISIBLE,
  INDEX `fk_Tec_Especialidades_Tipo_Incidente1_idx` (`Tipo_Incidente_idTipo_Incidente` ASC) VISIBLE,
  CONSTRAINT `fk_Tec_Especialidades_Tipo_Incidente1`
    FOREIGN KEY (`Tipo_Incidente_idTipo_Incidente`)
    REFERENCES `mydb`.`Tipo_Incidente` (`idTipo_Incidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Apellido` VARCHAR(60) NOT NULL,
  `DNI` INT NOT NULL,
  `CUIL` INT NOT NULL,
  `Edad` INT NOT NULL,
  `Telefono` INT NULL,
  `Email` VARCHAR(45) NULL,
  `Direccion` VARCHAR(60) NOT NULL DEFAULT 'Avenida Falsa 123',
  `Localidad` VARCHAR(45) NOT NULL,
  `Incidente_idIncidente` INT NOT NULL,
  `Incidente_Tipo_Incidente_idTipo_Incidente` INT NOT NULL,
  PRIMARY KEY (`idClientes`, `Incidente_idIncidente`, `Incidente_Tipo_Incidente_idTipo_Incidente`),
  UNIQUE INDEX `Nombre_Apellido_UNIQUE` (`Nombre_Apellido` ASC) VISIBLE,
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  UNIQUE INDEX `CUIL_UNIQUE` (`CUIL` ASC) VISIBLE,
  INDEX `fk_Clientes_Incidente1_idx` (`Incidente_idIncidente` ASC, `Incidente_Tipo_Incidente_idTipo_Incidente` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Incidente1`
    FOREIGN KEY (`Incidente_idIncidente` , `Incidente_Tipo_Incidente_idTipo_Incidente`)
    REFERENCES `mydb`.`Incidente` (`idIncidente` , `Tipo_Incidente_idTipo_Incidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicios` (
  `idServicios` INT NOT NULL,
  `Nombre/Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idServicios`),
  UNIQUE INDEX `Tipo_UNIQUE` (`Nombre/Tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes_has_Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes_has_Servicios` (
  `Clientes_idClientes` INT NOT NULL,
  `Servicios_idServicios` INT NOT NULL,
  PRIMARY KEY (`Clientes_idClientes`, `Servicios_idServicios`),
  INDEX `fk_Clientes_has_Servicios_Servicios1_idx` (`Servicios_idServicios` ASC) VISIBLE,
  INDEX `fk_Clientes_has_Servicios_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_has_Servicios_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_Servicios_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `mydb`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tec_Especialidades_has_Tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tec_Especialidades_has_Tecnicos` (
  `Tec_Especialidades_idTec_Especialidades` INT NOT NULL,
  `Tecnicos_idTecnicos` INT NOT NULL,
  PRIMARY KEY (`Tec_Especialidades_idTec_Especialidades`, `Tecnicos_idTecnicos`),
  INDEX `fk_Tec_Especialidades_has_Tecnicos_Tecnicos1_idx` (`Tecnicos_idTecnicos` ASC) VISIBLE,
  INDEX `fk_Tec_Especialidades_has_Tecnicos_Tec_Especialidades1_idx` (`Tec_Especialidades_idTec_Especialidades` ASC) VISIBLE,
  CONSTRAINT `fk_Tec_Especialidades_has_Tecnicos_Tec_Especialidades1`
    FOREIGN KEY (`Tec_Especialidades_idTec_Especialidades`)
    REFERENCES `mydb`.`Tec_Especialidades` (`idTec_Especialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tec_Especialidades_has_Tecnicos_Tecnicos1`
    FOREIGN KEY (`Tecnicos_idTecnicos`)
    REFERENCES `mydb`.`Tecnicos` (`idTecnicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
